apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bradmccoydev
  namespace: default
  tags:
    - hi
  links:
    - url: blog.bradmccoy.io
      title: Blog
      icon: dashboard
spec:
  profile:
    displayName: Brad McCoy
    email: bradmccoydev@gmail.com
    picture: https://avatars.githubusercontent.com/u/25817813?s=400&v=4
  memberOf: [dev]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-www
  description: Ortelius Website
  annotations:
    github.com/project-slug: ortelius/website
    github.com/project-readme-path: README.md
    backstage.io/kubernetes-id: ortelius-www
    argocd/app-name: ingress-nginx
  tags:
    - platform
  links:
    - url: https://ortelius.io/
      title: Website
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-docs
  description: Ortelius Docs
  annotations:
    backstage.io/kubernetes-id: ortelius-docs
    github.com/project-slug: ortelius/ortelius-docs
    github.com/project-readme-path: README.md
  tags:
    - platform
  links:
    - url: https://docs.ortelius.io/
      title: Docs
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: production
---
