NAME: backstage-1668224478
LAST DEPLOYED: Sat Nov 12 13:41:20 2022
NAMESPACE: backstage
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: backstage/templates/app/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-1668224478-app
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
---
# Source: backstage/templates/backend/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-1668224478-backend
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: backstage/templates/backend/configmap-app.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-1668224478-backend-app-config
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
data:
  app-config.yaml: |
    app:
      baseUrl: http://localhost:8080
      title: Ortelius Backstage
    backend:
      baseUrl: http://localhost:8080
      cors:
        credentials: true
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        origin: http://localhost:8080
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          password: ${POSTGRES_PASSWORD}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
      listen:
        port: 7007
    organization: {}
    techdocs:
      builder: external
---
# Source: backstage/templates/app/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backstage-1668224478-app
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/component: app
---
# Source: backstage/templates/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backstage-1668224478-backend
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/component: backend
---
# Source: backstage/templates/app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-1668224478-app
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: backstage-1668224478
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage
        app.kubernetes.io/instance: backstage-1668224478
        app.kubernetes.io/component: app
    spec:
      imagePullSecrets:
        - name: ghcr
      serviceAccountName: backstage-1668224478-app
      containers:
        - name: backstage
          image: ghcr.io/ortelius/backstage/app:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_CONFIG_app_title
              value: "Ortelius Backstage"
            - name: APP_CONFIG_app_baseUrl
              value: http://localhost:8080
            - name: APP_CONFIG_backend_baseUrl
              value: "http://localhost:8080"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
---
# Source: backstage/templates/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-1668224478-backend
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: backstage-1668224478
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
        checksum/config: 8ce121d8440fc962b30bf59af81f511110e312d5d990cb259e483fcac8f64597
      labels:
        app.kubernetes.io/name: backstage
        app.kubernetes.io/instance: backstage-1668224478
        app.kubernetes.io/component: backend
    spec:
      imagePullSecrets:
        - name: ghcr
      serviceAccountName: backstage-1668224478-backend
      containers:
        - name: backstage
          image: ghcr.io/ortelius/backstage/backend:0.0.1
          imagePullPolicy: IfNotPresent
          env:
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          volumeMounts:
            - mountPath: /app/app-config.yaml
              name: config
              subPath: app-config.yaml
      volumes:
        - name: config
          configMap:
            name: backstage-1668224478-backend-app-config
---
# Source: backstage/templates/app/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-1668224478-app
  labels:
    helm.sh/chart: backstage-0.0.2
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage-1668224478
    app.kubernetes.io/version: "0.0.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  rules:
    - host: "backstage.ortelius.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage-1668224478-app
                port:
                  number: 80
