name: CI Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'packages/app/**'
      - 'Dockerfile.app'
      - 'yarn.lock'
      - 'package.json'
    paths-ignore:
      - "**.md"

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write
  actions: read

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      COSIGN_EXPERIMENTAL: 1
      IMAGE_NAME_FRONTEND: ghcr.io/ortelius/backstage/app:0.0.1

    outputs:
      image-digest-frontend: ${{ steps.container_info.outputs.image-digest-frontend }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Nodejs and npm
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: 'npm'

    - name: Setup yarn
      run: npm install -g yarn

    - name: Setup Nodejs with yarn caching
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: yarn

    - run: yarn install --immutable --immutable-cache --check-cache
    - run: yarn tsc
    - run: yarn lint:all
    - run: yarn test:all
    - run: yarn build

    - name: Upload app artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: packages/app/dist
        retention-days: 5
        if-no-files-found: error

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Build & Push Docker Image Frontend
      run: |
        revision="$(git rev-parse "${GITHUB_REF_NAME:-HEAD}")"
        DOCKER_BUILDKIT=1 docker build \
         -t "${IMAGE_NAME_FRONTEND}" -f ./Dockerfile.app \
         --label "org.opencontainers.image.source=https://github.com/ortelius/backstage/packages/app" \
         --label "org.opencontainers.image.created=$(date --iso-8601=seconds)" \
         --label "org.opencontainers.image.title=Ortelius Backstage Frontend" \
         --label "org.opencontainers.image.revision=${revision}" \
         --label "org.opencontainers.image.version=${GITHUB_REF_NAME}" \
         --label "org.opencontainers.image.vendor=ortelius" \
          .

    - name: Run Trivy vulnerability scanner frontend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ortelius/backstage/app:0.0.1'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: '${{matrix.arch}}-container-trivy-results-frontend.sarif'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'

    - name: Upload Trivy SARIF report to GitHub Security tab frontend
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: '${{matrix.arch}}-container-trivy-results-frontend.sarif'
        category: trivy-${{matrix.arch}}

    - uses: anchore/sbom-action@v0
      with:
        image: "ghcr.io/ortelius/backstage/app:0.0.1"

    - name: Docker Push Frontend
      run: |-
        docker push --all-tags ghcr.io/ortelius/backstage/app

    - name: Get container info Frontend
      id: container_info_frontend
      run: |
        image_digest="$(docker inspect "${IMAGE_NAME}" --format '{{ index .RepoDigests 0 }}' | awk -F '@' '{ print $2 }')"
        echo "::set-output name=image-digest-frontend::${image_digest}"
