name: Package

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: variables
        run: |
          echo '::set-output name=artifact_path::packages/${{ inputs.type }}/dist'
          echo '::set-output name=dockerfile::./packages/${{ inputs.type }}/Dockerfile'
          echo '::set-output name=image::ghcr.io/ortelius/backstage/${{ inputs.type }}:0.0.1'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.type }}
          path: ${{ steps.variables.outputs.artifact_path }}

      - name: Set up Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.variables.outputs.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.variables.outputs.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
